### ISSUE TITLE
Exception thrown in contract code in Step 4/5

### ISSUE THREAD

**Issue by DaniellMesquita** [keep-network/tbtc-dapp#238]
### Description:
I don't know if it is because of concurrent deposits or if it is an unrelated bug. See the "Additional context" heading.

### Steps to reproduce the behavior:
Concurrent deposits?

### Expected behavior:
Doesn't applies.

### Environment details:
Doesn't applies.

### Additional context:
Possibly related with: https://github.com/keep-network/tbtc-dapp/issues/237

### Screenshots
![image](https://user-images.githubusercontent.com/6765277/87259141-702b5480-c47f-11ea-8770-9445d1b47276.png)

### Console logs
[console-export-2020-7-12_20-35-23.txt](https://github.com/keep-network/tbtc-dapp/files/4909915/console-export-2020-7-12_20-35-23.txt)

**Comment by Shadowfiend** [comment]
Hard to tell for sure because of the issue I note in [this comment](https://github.com/keep-network/tbtc-dapp/issues/258#issuecomment-663536507).

That said, this may also have been a difficulty mismatch issue (see [this comment](https://github.com/keep-network/tbtc-dapp/issues/248#issuecomment-663566632)). We're toggling a few switches for the next release that'll hopefully get some clearer error messages in the mix for us in these cases---I'm going to close this issue for now since it's hard to know what exactly caused it at this stage. The clearer errors should help if and when you run into it again.

Thanks for the report!
