### ISSUE TITLE
Exception in contract tBTC with Metamask

### ISSUE THREAD

**Issue by TeRvErO** [keep-network/tbtc-dapp#258]
![image](https://user-images.githubusercontent.com/23222991/87344213-b0a9d180-c556-11ea-94b1-1818182a72f4.png)

After multiple tries to deposit eth on the second step, I get this exception in contract shown in Metamask. My balance is ~6 ETH.

**Comment by Shadowfiend** [comment]
Yeah, unfortunately due to some limitations in Metamask, the only way to see the underlying error is to confirm the transaction and see what error it comes back with. Most likely you were trying to open a deposit during some pricing/bond issues we were having on Ropsten last week (see keep-network/keep-ecdsa#504). Closing this issue for now, but please feel free to reopen if you're still seeing something similar.
