### ISSUE TITLE
Redeem function Step 1: Clarify / Change what the TDT ID is, where to get it

### ISSUE THREAD

**Issue by ramaruro** [keep-network/tbtc-dapp#261]
When you use the Redeem function (https://dapp.test.tbtc.network/redeem) in Step 1 it asks "What was your TDT ID?".
It is unclear for a user what the TDT ID is. If that is the User's Ethereum Address, it should say so. TDT ID is confusing.

If it is not the Ethereum Address, it should clearly guide to where to find it.

![Redeem](https://user-images.githubusercontent.com/68167410/87457451-04a3cd00-c5ce-11ea-8739-608bca7ef3d1.JPG)

**Comment by Shadowfiend** [comment]
The TDT id is clearly noted at the end of the deposit flow, but is an awkward component anyway. As I mentioned in #243 which was centered around the same thing, we're looking at giving users better tools for managing their deposits, and phasing the TDT id into the background instead of making it the primary user approach to referencing a deposit is a core part of that. You can see some early work in this department in #222.

Thanks for the detailed thoughts!

**Comment by culgin** [comment]
Same thoughts. I actually did not jot down my TDT ID at the end of the flow and now I have problem doing a redemption. Intuitively, the TDT ID should be the ERC721 tokenID that can be easily found on etherscan.

**Comment by ramaruro** [comment]
I assume some people will sell their tBTC. Whoever buys that and wants to redeem, should be able to do it. How would that person find the TDT? In any case, it makes it complicated.

**Comment by Shadowfiend** [comment]
> How would that person find the TDT? In any case, it makes it complicated. 

Yep, definitely something that's on the radar. I'm closing issues around this as the goal of phasing TDT ids into the background is captured in 222---will announce on Discord when the work from that starts rolling out so folks can give thoughts!
