### ISSUE TITLE
UX improvements Redeem TDT - explain TDT field

### ISSUE THREAD

**Issue by bonsfi** [keep-network/tbtc-dapp#278]
Explain what the TDT ID is and how to find it. 

For example, I have ERC20 tBTC tokens in my account but also ERC721 tokens and both have an ID. Then I do not know if I can redeem 1) TDT ERC721 tokens which were failed transactions when I sent testnet BTC or 2) the tBTC dapp only works with ID's of ERC20 tBTC.

It would be nice if you could clarify how to get the ID. Please see screenshot:

<img width="495" alt="Screenshot 2020-07-17 at 19 57 31" src="https://user-images.githubusercontent.com/12712595/87816661-fffa4580-c867-11ea-89f9-f4df9e3441af.png">

**Comment by Shadowfiend** [comment]
> TDT ERC721 tokens which were failed transactions when I sent testnet BTC

Generally you cannot redeem a deposit if you did not succeed in funding it in the first place. TDTs are the nonfungible token, however.

With that said, we're working to make the TDT a largely invisible part of this process in the dApp; this is currently being folded into #222 as we introduce UI-based tracking of deposits that are in the vending machine and deposits you own (rather than requiring ids of tokens).

Closing this issue for now since it's part of upcoming work, even though we'll be addressing it in a slightly different way.
