### ISSUE TITLE
Insufficient signer bonds to cover setup fee

### ISSUE THREAD

**Issue by LexPrime** [keep-network/tbtc-dapp#290]
### Description:
Error on step 2 initial deposit

### Steps to reproduce the behavior:
1. Go to https://dapp.test.tbtc.network/
2. Deposit
3. Connect Metamask
4. Choose 0.01Btc
5. Create address 
6. Error in Metamask  
![tbtc error metamask 2020-07-23 222646](https://user-images.githubusercontent.com/17300737/88334067-de063480-cd39-11ea-9284-5024158e2adc.png)
7. Transaction error
![tbtc error 2020-07-23 222646](https://user-images.githubusercontent.com/17300737/88334401-61c02100-cd3a-11ea-9fa7-1c5915cd255e.png)
![tbtc error1 2020-07-23 222646](https://user-images.githubusercontent.com/17300737/88334535-9c29be00-cd3a-11ea-9a03-b2296145e63f.png)
8. After that refresh https://dapp.test.tbtc.network/deposit/new and new error appears
![tbtc error2 2020-07-23 222646](https://user-images.githubusercontent.com/17300737/88335212-97b1d500-cd3b-11ea-8357-a809577a8af5.png)

### Environment details:
OS: Windows 10 Pro, Version 2004, build 19041.330, 64 bit OS  
Web Browser: Mozilla Firefox, Version 78.0.2 (Official Build) (64-bit), Brave v 1.11.97
Wallet: Metamask (Chrome extension), Version 8.0.5

### Console.log
[tbts-log-2020-7-23_22-44-11.txt](https://github.com/keep-network/tbtc-dapp/files/4968590/tbts-log-2020-7-23_22-44-11.txt)

**Comment by Shadowfiend** [comment]
Thanks for the issue! This is actually expected behavior when there are not enough bonded signers available in the system to back your new deposit. The error itself could definitely use some clarification and massaging, and ideally you would know this is something that could happen before starting the process in the first place. We're tracking some of that in #260; closing this issue in its favor, though we can reopen here if we decide there's something different going on.
