### ISSUE TITLE
Minting Capacity needs to be reserved at the beggining for all steps (TDT creation -->tBTC conversion)

### ISSUE THREAD

**Issue by ramaruro** [keep-network/tbtc-dapp#309]
The specific issue of the process stopping at step 4 is reported here:
https://github.com/keep-network/tbtc-dapp/issues/305
An example of a transaction stuck at Step 4 (creation of TDT) is this one:
https://dapp.test.tbtc.network/deposit/0x35EBcF3D2990c97694F4b62160Bce3571Ed0f2DA/prove

So now you are stuck with TDT tokens. Supposedly you can convert them to tBTC later.
There should be an "agent" that reserves the capacity to mint until the end from the beginning, which involves:
* Creating the Signing Group with enough ETH Collateral to mint
 --> If this is available, the whole process should finish until the final tBTC
 --> If there is not enough ETH bonding capacity, it should abort the whole process at the beginning

Total capacity for minting should be defined by total available Collateral available, not a hardcoded value as it seems right now.
![image](https://user-images.githubusercontent.com/68167410/88483031-c4780f00-cf2a-11ea-916e-08ee2d38c491.png)

**Comment by Shadowfiend** [comment]
Minting capacity is hardcoded intentionally, as a way to reduce risk in the early days of the system. It ramps up in predetermined phases, and is specifically about minting capacity rather than deposit capacity. Read more [in our blog post](https://blog.keep.network/an-update-on-tbtcs-launch-9403ad82970f) regarding the graduated supply cap.

Closing this issue, as everything here is behaving as expected and will not be changing. We do understand the need for folks to get a feel for where current system capacity is during the process, as well as current bond capacity; we're tracking that via #260.
