### ISSUE TITLE
Error Redeeming Bond: Step 2/6 - "Number can only safely store up to 53 bits"

### ISSUE THREAD

**Issue by jasonchewyl** [keep-network/tbtc-dapp#310]
**Description:**
Redemption crashes on Step 2/6 while following standard behaviors, throws this message:

Error redeeming bond
We’re waiting for you to confirm invoice details in your Wallet.

***Number can only safely store up to 53 bits***

https://dapp.test.tbtc.network/deposit/0x91BE5e83A4FfA93dca0f00eb1157A3b0D779E359/redemption

**Screenshots**

![image](https://user-images.githubusercontent.com/53902721/88486353-adc7cb80-cfaf-11ea-9783-eaff98ca8c17.png)

**Note:**
I've read these threads but I still don't understand **whats the solution?**
[github.com/keep-network/tbtc-dapp/issues/245](https://github.com/keep-network/tbtc-dapp/issues/245)
[github.com/keep-network/tbtc.js/issues/57](https://github.com/keep-network/tbtc.js/issues/57)

**Comment by bonsfi** [comment]
I have the same error. 

OS: Windows 10
Web Browser: Firefox, 78.0.2 (64-bit)
Wallet: Metamask (Firefox extension), Version 8.0.4

**Comment by ironng** [comment]
@jasonchewyl Thanks for reporting! This has been fixed by https://github.com/keep-network/tbtc.js/pull/59. Please refer to the commit message in https://github.com/keep-network/tbtc.js/pull/59/commits/81a86629a75feb4dec2a76ed97f327e8ee77bc95 for clarification. Let us know if you have any other questions!

Closing as a duplicate.

**Comment by Shadowfiend** [comment]
Of note, we'll be deploying this later this week; it's blocked on a couple of other tidbits right now.
