### ISSUE TITLE
dApp reads built-in wallet as Metamask and it works

### ISSUE THREAD

**Issue by JaviAnibarro** [keep-network/tbtc-dapp#320]
As we can see Opera browser has its own built-in crypto wallet based on Web 3 just like MEW.
So I installed Opera browser to test it and it worked fine but dApp read it as Metamask,
The question is, why would dApp reject MEW if it supports Web 3?
and based on [@251](https://github.com/keep-network/tbtc-dapp/issues/251#issuecomment-660701643), currently, dApp only supports Metamask.

What could be the reason behind this? 
(Tested MEW and tried to connect it, but it's still stuck while Opera built-in crypto wallet succeed connecting to the dApp)

![image](https://user-images.githubusercontent.com/67586661/88726481-ffab5580-d157-11ea-85ed-ec91b42e24ec.png)    
![image](https://user-images.githubusercontent.com/67586661/88726602-3e411000-d158-11ea-88b1-9e9bad7ff6b8.png)

**Comment by Shadowfiend** [comment]
Not sure if I'm misunderstanding here, but this sounds like a thing that works, not a thing that doesn't? If it works, please don't open issues on it. If the observation is data for the MyEtherWallet issue, we can discuss those in #251 . Going to close this for now, but please feel free to reopen if I've misunderstood the issue.

**Comment by JaviAnibarro** [comment]
Well @Shadowfiend , I was talking about dApp that reads Web 3 based wallet as Metamask. Is it intended for dApp to show this behaviour?
And the reason why I connected it with that issue because matt said dApp only supports Metamask while in here we can see it can load up another wallet.

**Comment by Shadowfiend** [comment]
We only test with Metamask, but I'm not surprised other Web3 wallets work (in fact, I'm surprised when they don't). Right now, the UI specifically calls out Metamask because we're not planning on extending our testing to other Web3 providers yet, even though I'd like for our support to be decent enough. Once we've got independent confirmation from a few places that things work as expected on other wallets, I think we'll look at expanding the UI's terminology to reflect that. In the meantime, though, I'm hesitant to claim that we do unless we're fairly confident that it's the case.

**Comment by JaviAnibarro** [comment]
Ah ok, it looks like a missunderstanding in my part after hearing only support Metamask and the UI shows Metamask but load up Web 3(Here I thought there’s a bug preventing dApp to block web 3).
