### ISSUE TITLE
dApp Redeem: [Error redeeming bond: does not have required balance]

### ISSUE THREAD

**Issue by JaviAnibarro** [keep-network/tbtc-dapp#341]
dApp refused to redeem my TBTC if it's not fully rounded to 1 or other sizers.
Is it intended to be like this? how to redeem it?

**Steps to reproduce the behavior:**
1. Go to https://dapp.test.tbtc.network/
2. Click on Redeem
3. Connect your wallet
4. Input the details (TDT ID and Preferred testnet BTC address)
5. See error

**Environment details:**
OS: Windows 10 Pro, 64 bit OS
Web Browser: Google Chrome (64-bit)
Wallet: Metamask (Google Chrome Extension)

![redeem](https://user-images.githubusercontent.com/67586661/89955926-4623a880-dc5e-11ea-8b7c-ce2dca8c93ce.PNG)

Log can be found here:
[tbtc-dapp-v0.18.0-rc-log-1597185582736.txt](https://github.com/keep-network/tbtc-dapp/files/5059803/tbtc-dapp-v0.18.0-rc-log-1597185582736.txt)

**Comment by Ostrovmaria80** [comment]
Can confirm everyone encountering the same issue.
Here are some transactions from my friend's wallet:
https://ropsten.etherscan.io/tx/0xad593feb12e8b5b6958fc5fdda8216e29e189458b5fec52b878cab91dd356f0b
Minted 0.9995 TBTC
https://ropsten.etherscan.io/tx/0x17730cf9147723405202e97bac8783bfaae355059543d471bdf527ac33369fd9
Redeemed 1 whole TBTC

So you always need to mint at least 2 TBTC to redeem 1, since you don't receive rounded number.

**Comment by Shadowfiend** [comment]
This is correct and expected behavior. You need to have 1 TBTC to redeem a 1 BTC deposit you opened, and minting off of a 1 BTC deposit only gets you 0.9995 TBTC.

**Comment by JaviAnibarro** [comment]
Then how to redeem the rest of it? dApp refused my order.
