### ISSUE TITLE
3 Redeems sending testBTC all in 1 single transaction and giving same link

### ISSUE THREAD

**Issue by Ostrovmaria80** [keep-network/tbtc-dapp#348]
### Description:
This issue happens when trying simultaneously to redeem 3 different TDTs. Please see screenshots: all 3 redeem transactions display 1 single testBTC transaction. Which probably also causes loss of testBTC for users

### Additional context:
https://blockstream.info/testnet/tx/758e88b6bf2421f2dd7075b92555ecc5ce3578ac601a97cb62a5c0674e102a4d

### Screenshots
![1in3 1](https://user-images.githubusercontent.com/66871108/90273572-d54fdc80-de67-11ea-9016-0db20643b99c.jpg)
![1in3 2](https://user-images.githubusercontent.com/66871108/90273574-d7b23680-de67-11ea-8949-f6d3ea8ca567.jpg)
![1in3 3](https://user-images.githubusercontent.com/66871108/90273578-d8e36380-de67-11ea-8a88-2ba1bcc309fc.jpg)

**Comment by Shadowfiend** [comment]
Great catch! This is a known issue in tbtc.js, due to the fact that it doesn't currently disambiguate well between different transactions to the same receiving address during redemption (embodied in [this FIXME](https://github.com/keep-network/tbtc.js/blob/master/src/Redemption.js#L171-L173), for the curious). It's on my snipe list, thanks for the report!
