### ISSUE TITLE
The dapp allows you to use someone else's TDT ID for redemption

### ISSUE THREAD

**Issue by Tuzemunez** [keep-network/tbtc-dapp#351]
During redemption, you can use any previously unused TDT ID, not just the owner TDT ID. It seems to me that this is not correct, or I did not fully understand the essence of TDT)

**Comment by Shadowfiend** [comment]
This is only true for TDTs that have been used to mint TBTC. These TDTs no longer belong to an individual owner; instead they belong to the tBTC system, and may be redeemed by anyone. See the [Minting section of the spec](https://docs.keep.network/tbtc/#minting) for a more detailed technical explanation.

Closing this issue since it's working as expected, but let us know if there are details that would merit reopening!

**Comment by Tuzemunez** [comment]
Ok, thanks for the explanation!
